#!/bin/bash

# Source global definitions
if [ -f /etc/bashrc ];
then
	source /etc/bashrc
fi

# import env variables
for env_file in ~/.*.env;
do
	source $env_file
done
export PATH=$HOME/.toolbox/bin:$PATH
