[components]
  all = [
    "cmdLineEssentials",
    "helixEditor",
    "rustToolchainStable",
    "rustToolchainNightly",
    "zellij"
  ]
  minimal = []
  default = [
    "cmdLineEssentials",
    "helixEditor",
    "rustToolchainStable",
    "zellij"
  ]


