[components]
all = [
  "cmdLineEssentials",
  "gitDelta",
  "helixEditor",
  "rustToolchainStable",
  "rustToolchainNightly",
  "zellij"
]
default = [
  "cmdLineEssentials",
  "gitDelta",
  "helixEditor",
  "rustToolchainStable",
  "zellij"
]
minimal = []

