[components]
all = [
  "buildEssentials",
  "cmdLineEssentials",
  "rustToolchainStable",
  "rustToolchainNightly"
]
default = [
  "buildEssentials",
  "cmdLineEssentials",
  "rustToolchainStable"
]
minimal = []

