toolchains = [
  "rustToolchainStable",
  "rustToolchainNightly"
]

[packageGroup.buildEssentials.al2]
yum = [
  "autoconf",
  "automake",
  "cmake",
  "gcc",
  "gcc+c++",
  "glibc-devel",
  "openssl-devel",
  "perl-core",
  "tree",
  "vim",
  "wget"
]
