format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$package\
$aws\
$sudo\
$line_break\
$status\
$container\
$shell\
$character"""

right_format = """
$time\
$cmd_duration"""

[aws]
format = '[$symbol($profile )(\($region\))]($style) '
symbol = '☁️ '
style = 'purple'

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "

[directory]
style = "blue"
truncate_to_repo = false
truncation_length = 8
truncation_symbol = "…/"
before_repo_root_style = "bright-black"
repo_root_style = "bold cyan"

[cmd_duration]
format = "[$duration]($style)"

[fill]
symbol = ' '

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[hostname]
ssh_symbol = ""
format = "[$hostname]($style) "
style = "bright-black"

[time]
format = '[$time]($style) '
style = "bright-black"
disabled = false

[nodejs]
symbol = "[⬢](bold green) "

[username]
style_user = "bright-black"
format = "[$user&]($style)"
