#!/bin/zsh

# INTERNAL UTILITY FUNCTIONS {{{1
_error() {
	echo
	echo "[31;1m$*[0m"
	echo
}

# INTERNAL CACHE SETUP {{{1
ZSHRC_CACHE=~/.zshrc.cache
ZSHRC_CACHE_BYPASS_FILE=~/.zshrc.cache.bypass
unset ZSHRC_CACHE_CHECK
__cache_guard="E7WUH"

__cache() {
	if [[ $1 != ${__cache_guard} ]]; then
		echo "Cannot call __cache directly"
		return
	fi
	shift
	echo $* >> ${ZSHRC_CACHE}
	$*
}

__cache_no_op() {}

_cache_gen_check() {
	return !${+ZSHRC_CACHE_CHECK}
}

if [[ -n ${ZSHRC_CACHE_BYPASS} || -e  ${ZSHRC_CACHE_BYPASS_FILE} ]]; then
	ZSHRC_CACHE_CHECK=BYPASS
	alias _cache=''
elif [[ ! -e ${ZSHRC_CACHE} ]]; then
	ZSHRC_CACHE_CHECK=GEN
	alias _cache='noglob __cache ${__cache_guard}'
else
	alias _cache='__cache_no_op'
fi

# ENVIRONMENT {{{1
source ~/.dotfiles.env
export ZSHRC_LOCAL=~/.config/local/zsh/zshrc
export ZSHRC_LOCAL_BEFORE=~/.config/local/zsh/zshrc.before.zsh

if [[ ! -d ${dotfiles} ]]; then
	_error "currently dotfiles must be installed for this to work; exiting"
	return 1
fi

export ZPLUG_HOME=${dotfiles}/external/zsh/zplug

if [[ ! -f ${ZPLUG_HOME}/init.zsh ]]; then
	_error "currently zplug must be installed for this to work; exiting"
	return 1
fi

if [[ -e ${ZSHRC_LOCAL_BEFORE} ]]; then
    . ${ZSHRC_LOCAL_BEFORE}
fi

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000

export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}
source ~/.fzf.zsh

export LS_COLORS='di=34:ln=35:so=36:pi=33:ex=32:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43'
export LSCOLORS='exfxgxdxcxegedabagacad'
export CLICOLOR=1

# ALIASES {{{1
alias dotfiles-update='${dotfiles}/dotfiles/setup.sh --install'
alias g='git'
alias gA='git add .'
alias ga='git add'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit --amend'
alias gct='git commit -m "TMP"'
alias gcm='git commit -m'
alias gdc='git diff --cached'
alias gdd='git difftool'
alias gddc='git difftool --cached'
alias gf='git fetch'
alias gr='git rebase -i'
alias gs='git status'
alias pd='popd'
alias isodate='date +"%FT%TZ"'
alias ita='tmux -CC new-session -A -s'
alias reload='. ~/.zshrc'
alias reloadf='rm -rf ${ZSHRC_CACHE} && . ~/.zshrc'
alias reloadff='rm -rf ${ZSHRC_CACHE} && zplug clear && . ~/.zshrc'
alias ta='tmux new-session -A -s'
alias td='tmux detach -s'
alias tl='tmux list-sessions'
alias tk='tmux kill-session -t'
alias vf='nvim $(fzf)'
alias vi='nvim'
alias vim='nvim'
alias zshrc-time='time  zsh -i -c exit'
alias zshrc-time-bp='ZSHRC_CACHE_BYPASS=1;time  zsh -i -c exit'
alias zshrc-time-f='rm -rf ${ZSHRC_CACHE}; time  zsh -i -c exit'
alias zshrc-time-ff='rm -rf ${ZSHRC_CACHE}; zplug clear; time  zsh -i -c exit'

# FUNCTIONS {{{1

zshrc-getzplug() {
	if [[ -d ${ZPLUG_HOME} ]]; then
		rm -rf ${ZPLUG_HOME}
	fi

	git clone https://github.com/zplug/zplug ${ZPLUG_HOME}
}

# PLUGINS {{{1

source ${ZPLUG_HOME}/init.zsh
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
# zplug "oskarkrawczyk/honukai-iterm-zsh", as:theme
zplug mafredri/zsh-async, from:github
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

if ! zplug check; then
    zplug install
fi

# ZSH OPTIONS {{{1

# cd
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushd_silent

# completion
setopt always_to_end
setopt auto_menu
setopt complete_in_word

# history
setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt hist_verify

# other
setopt extended_glob
setopt no_beep

# SOURCE OTHER FILES AND LOAD PLUGINS {{{1
if _cache_gen_check; then
    for env_file in ~/.*.env(N); do
	if [[ $env_file != *.dotfiles.env ]]; then
	    _cache . $env_file
	fi
    done
    unset env_file
fi

if [[ -e ${ZSHRC_LOCAL} ]]; then
	. ${ZSHRC_LOCAL}
fi

if ! _cache_gen_check; then
	source $ZSHRC_CACHE
fi

zplug load

# CLEANUP {{{1
unalias _cache
unhash -f __cache
unhash -f __cache_no_op
unhash -f _cache_gen_check
unset ZSHRC_CACHE
unset ZSHRC_CACHE_BYPASS_FILE
unset ZSHRC_CACHE_CHECK
unset __cache_guard

# vim:ft=zsh:foldmethod=marker
