# import env variables
for env_file in ~/.*.env;
do
	source $env_file
done

for zsh_file in "${dotfiles}/*/*.zsh";
do
	source $zsh_file
done

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt beep
bindkey -v
