# .bashrc

# Source global definitions
if [ -f /etc/bashrc ];
then
	source /etc/bashrc
fi

# import env variables
for env_file in ~/.*.env;
do
	source $env_file
done

for bash_file in ${dotfiles}/*/*.bash;
do
	source $bash_file
done
